"""add_is_external_to_doctors

Revision ID: 27efd28f6bd1
Revises: a5c81cf5d030
Create Date: 2026-03-27 18:49:28.314962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27efd28f6bd1'
down_revision: Union[str, Sequence[str], None] = 'a5c81cf5d030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_external', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'is_external')
    # ### end Alembic commands ###
