"""Add ON DELETE CASCADE to shift_assignments.doctor_id

Revision ID: 3addaa9af519
Revises: f8d08b10001d
Create Date: 2026-02-27 18:52:08.667983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3addaa9af519'
down_revision: Union[str, Sequence[str], None] = 'f8d08b10001d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    table_exists = conn.execute(
        sa.text("SELECT to_regclass('public.shift_assignments')")
    ).scalar()

    if table_exists is None:
        # 本番DBでは手動作成済みのため、ローカル等の新規DBではここで作成する
        op.create_table(
            'shift_assignments',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('date', sa.Date(), nullable=False),
            sa.Column('doctor_id', sa.UUID(), nullable=False),
            sa.Column('shift_type', sa.String(length=20), nullable=False),
            sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
        )
    else:
        op.drop_constraint(op.f('shift_assignments_doctor_id_fkey'), 'shift_assignments', type_='foreignkey')
        op.create_foreign_key(None, 'shift_assignments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('shift_assignments_doctor_id_fkey'), 'shift_assignments', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
