"""add unavailable_day shift_target and soft_penalty

Revision ID: c3cddc2718ad
Revises: 2a282ee77c3b
Create Date: 2026-03-06 01:38:52.499071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cddc2718ad'
down_revision: Union[str, Sequence[str], None] = '2a282ee77c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
