"""Add doctor score columns

Revision ID: e617c9afe632
Revises: 3addaa9af519
Create Date: 2026-02-27 23:57:43.774677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e617c9afe632'
down_revision: Union[str, Sequence[str], None] = '3addaa9af519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gap5', sa.Integer(), nullable=False),
    sa.Column('gap6', sa.Integer(), nullable=False),
    sa.Column('pre_clinic', sa.Integer(), nullable=False),
    sa.Column('sat_consec', sa.Integer(), nullable=False),
    sa.Column('score_balance', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('sunhol_3rd', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('doctors', sa.Column('min_score', sa.Float(), nullable=True))
    op.add_column('doctors', sa.Column('max_score', sa.Float(), nullable=True))
    op.add_column('doctors', sa.Column('target_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'target_score')
    op.drop_column('doctors', 'max_score')
    op.drop_column('doctors', 'min_score')
    op.drop_table('weight_presets')
    # ### end Alembic commands ###
